pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=codecov/project
      - status-success=codecov/patch
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
