--- 
language: scala

install:
  - |
    # From: https://eed3si9n.com/sbt-1.4.9
    # Remove this when https://github.com/travis-ci/travis-build/pull/1980 is fixed
    export SBT_LAUNCHER=1.4.9
    export SBT_OPTS="-Dfile.encoding=UTF-8"
    curl -L --silent "https://github.com/sbt/sbt/releases/download/v$SBT_LAUNCHER/sbt-$SBT_LAUNCHER.tgz" > $HOME/sbt.tgz
    tar zxf $HOME/sbt.tgz -C $HOME
    sudo rm /usr/local/bin/sbt
    sudo ln -s $HOME/sbt/bin/sbt /usr/local/bin/sbt

script: >
 sbt ++$TRAVIS_SCALA_VERSION check mdoc $COVERAGE $PROJECT/test $COVERAGE &&
 cd target &&
 git clone https://github.com/lemonlabsuk/scala-uri-demo.git &&
 cd scala-uri-demo &&
 sbt -Dscala.ver=$TRAVIS_SCALA_VERSION -Dscala.uri.ver=3.5.0 test &&
 cd "$TRAVIS_BUILD_DIR"

jdk:
  - openjdk8

jobs:
  include:
    - scala: [ 3.0.1 ]
      env: PROJECT=scalaUriJVM COVERAGE="" COVERAGE_REPORT=""
# Unable to run the tests for Scala.js + Scala3. Same issue as described here:
# https://github.com/softwaremill/quicklens/issues/67
# TODO: Re-enable once resolved
#    - scala: [ 3.0.1 ]
#      env: PROJECT=scalaUriJS COVERAGE="" COVERAGE_REPORT=""
    - scala: [2.13.6]
      env: PROJECT=scalaUriJVM COVERAGE=coverage COVERAGE_REPORT=coverageReport
    - scala: [2.13.6]
      env: PROJECT=scalaUriJS COVERAGE=coverage COVERAGE_REPORT=coverageReport
    - scala: [2.12.14]
      env: PROJECT=scalaUriJVM COVERAGE=coverage COVERAGE_REPORT=coverageReport
    - scala: [2.12.14]
      env: PROJECT=scalaUriJS COVERAGE=coverage COVERAGE_REPORT=coverageReport

before_script:
  - nvm install 10 # nodejs < 10 fails finding URL class

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
