--- 
language: scala
script: "sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport"

jdk:
  - oraclejdk8

scala:
  - 2.11.8
  - 2.12.3

sudo: false # Enable new travis container-based infrastructure

after_success:
  - bash <(curl -s https://codecov.io/bash)
