--- 
language: scala
script: >
 sbt -Dscala.uri.ver=999-SNAPSHOT $COVERAGE ++$TRAVIS_SCALA_VERSION coverage test coverageReport publishLocal &&
 cd target &&
 git clone https://github.com/lemonlabsuk/scala-uri-demo.git &&
 cd scala-uri-demo &&
 sbt -Dscala.uri.ver=999-SNAPSHOT test &&
 sbt -Dscala.uri.ver=0.5.0 test

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.12.3
      env: COVERAGE=coverageOn
    - scala: 2.11.8
      env: COVERAGE=coverageOff

sudo: false # Enable new travis container-based infrastructure

after_success:
  - bash <(curl -s https://codecov.io/bash)
