--- 
language: scala
script: "sbt $COVERAGE ++$TRAVIS_SCALA_VERSION coverage test coverageReport"

jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.12.3
      env: COVERAGE=coverageOn
    - scala: 2.11.8
      env: COVERAGE=coverageOff

sudo: false # Enable new travis container-based infrastructure

after_success:
  - bash <(curl -s https://codecov.io/bash)
